source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "thin", "~> 1.8.1"
gem "async_sinatra", "~> 1.3.0"
gem "sinatra-activerecord", "~> 2.0.25"
gem "activerecord", "~> 7.0.3"
